name: Publish Docker image for new releases

on:
  push:
    branches: [ v0.9.9 ]
  pull_request:
    branches: [ v0.9.9 ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: scripts/Dockerfile
          tags: |
            onfinality/parachain:v0.9.9
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
